# Generated by Django 5.1.7 on 2025-03-31 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_alter_contacts_options_alter_products_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='contacts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.contacts', verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.products', verbose_name='Продукты'),
        ),
    ]
